### PR TITLE
Fixed travis

### PR DESCRIPTION
**Pull request by griswaldbrooks**
- Fixed travis build.
- Removed usb_cam, doMotor, and doGPS.
- Added build badge.
- Renamed ianthe_cone_finder_strategy.launch to cone_finder_strategy.launch.
- Renamed ianthe_robo_magellan.launch to robo_magellan.launch.
- Added cone_finder_strategy_node back to CMakeLists.txt.

### CODE REVIEW

**Comment by mwimble** [comment]
Cone_finder_node is being replaced with robo_magrllan. I may recreate ianthe launches for now as I use them to test code on my robot. It's okay what you did, though

**Comment by griswaldbrooks** [comment]
@mwimble just tell me what I should do now with regards to those launch files. I noticed that they were virtually identical. I want to get in something that looks like the right thing so I can keep travis going.

**Comment by mwimble** [comment]
You're fine with what you did. I'll work around you.

**Comment by griswaldbrooks** [comment]
@mwimble could you approve it then?

**Comment by mwimble** [comment]
Might be a hour or so

**Comment by griswaldbrooks** [comment]
np

**Pull request merged**
